### ISSUE TITLE
데이터 contrast 종류 관련 문의

### ISSUE THREAD

**Issue by caelum02** [LISTatSNU/FastMRI_challenge#12]
안녕하세요? 데이터셋 관련해 문의를 드리고 싶습니다.
모델 학습에 있어서 많은 기존의 연구 방법 다양한 종류의 contrast를 다 사용하는 듯 하여, SNU FASTMRI 대회의 train, test 데이터셋은 어떤 contrast의 MRI 영상인지 질문드리고 싶습니다. 감사합니다!

**Comment by jonghoyi75** [comment]
학습을 위한 데이터와 test 데이터 모두 T2 영상이라고 합니다.
