### ISSUE TITLE
서버 데이터 관련 이슈

### ISSUE THREAD

**Issue by robin5310** [LISTatSNU/FastMRI_challenge#139]
현재 다시 생성한 서버에서 root/input/train/image 의 h5 파일 일부와  kspace 파일 대부분이 없는 상태입니다. 이 경우 workspace를 다시 만드는 것이 맞을까요?

**Comment by HynwLee** [comment]
Terminate하였으니, 다시 만들어 보시기 바랍니다.

**Comment by robin5310** [comment]
해결됬습니다!
