### ISSUE TITLE
다른 팀의 pretrained network 질문

### ISSUE THREAD

**Issue by kb5kch2** [LISTatSNU/FastMRI_challenge#140]
안녕하세요

다른 팀에서 올린 pretrained network의 깃허브에 등록되어있지만 언급하지는 모델을 사용해도 괜찮은가요?

https://github.com/LISTatSNU/FastMRI_challenge/issues/125
위 글에서 언급된 모델은 recurrentvarnet, joint-icnet이지만 등록된 깃허브에 다른 모델들이 있어 문의 드립니다.

**Comment by jonghoyi** [comment]
지난번에 3개의 모델로 한정하기로 하여서 안됩니다.
