### ISSUE TITLE
Pretrained network의 Pretrained weight 사용 가능 문의

### ISSUE THREAD

**Issue by kb5kch2** [LISTatSNU/FastMRI_challenge#157]
안녕하세요

등록된 Pretrained network에서 제공하는 pretrained weight를 사용할 수 있는지 문의 드립니다.
pretrained weight가 뇌사진으로 학습된 경우, 외부 뇌 데이터를 학습에 사용한 것으로 간주되나요?

**Comment by HynwLee** [comment]
https://github.com/LISTatSNU/FastMRI_challenge/issues/112 
를 참고해 주시기 바랍니다.

**Comment by sjh97** [comment]
용어에 혼동이 있어 질문 드립니다.

network와 model, weight를 다른 것으로 생각하고 질문을 드렸는데 의미가 정확하게 전달되었는지 모르겠습니다.
예를 들어 facebook의 fasrMRI varnet을 사용했다면
    pretrained network = pretrained model = E2Evarnet (즉 architecture)
    pretrained weight = 뇌 데이터로 학습을 진행하여 만들어 놓은 weight 모음 (예를 들면 .ckpt나 .pt 파일)

정확하게 이해한 것이 맞나요?

**Comment by kb5kch2** [comment]
용어에 혼동이 있어 질문 드립니다.

network와 model, weight를 다른 것으로 생각하고 질문을 드렸는데 의미가 정확하게 전달되었는지 모르겠습니다.
예를 들어 facebook의 fasrMRI varnet을 사용했다면
pretrained network = pretrained model = E2Evarnet (즉 architecture)
pretrained weight = 뇌 데이터로 학습을 진행하여 만들어 놓은 weight 모음 (예를 들면 .ckpt나 .pt 파일)

제가 위 용어들을 정확하게 이해한 것이 맞나요?

**Comment by HynwLee** [comment]
네, pretrained network에 첨부된 weight 파일 (.ckpt, .pt)를 가져다 쓰셔도 됩니다. 물론, 해당 pretrained network가 등록되어 있어야 합니다.
