### ISSUE TITLE
kspace data read 오류

### ISSUE THREAD

**Issue by HyeonbeomChoi** [LISTatSNU/FastMRI_challenge#189]
안녕하세요, 챌린지 참가하고 있는 팀 Digital Catalyst 최현범입니다.

iabeng 28 node, lone-associate 워크스페이스에서 다음과 같이, kspace를 read하는 과정에서 오류가 발생하여 문의드립니다.
<img width="1327" alt="스크린샷 2023-07-21 오전 9 41 33" src="https://github.com/LISTatSNU/FastMRI_challenge/assets/102167841/034c5d6d-ff8a-4ae3-bb4a-8861a2de126d">

**Comment by wogur110** [comment]
안녕하세요, 2023 SNU FastMRI Challenge 조교 배재혁입니다.
현재, iabeng28 노드에 노드에 대해서 kspace 데이터 (train, val 포함)를 재배포하고 있으니, 2시간 정도 뒤에 확인해주시면 감사하겠습니다. 배포가 완료되는 대로 공지해드리겠습니다.

감사합니다.
배재혁 드림

**Comment by wogur110** [comment]
현재 (7/21 오후 1:27) iabeng28 노드에 대해서 kspace 데이터를 전부 재배포하였습니다. 한번 다시 테스트해보시고 알려주시면 감사하겠습니다.
배재혁 드림

**Comment by HyeonbeomChoi** [comment]
넵 정상적으로 train됩니다 감사합니다 !!
