### ISSUE TITLE
cv2 관련 오류

### ISSUE THREAD

**Issue by HyeonbeomChoi** [LISTatSNU/FastMRI_challenge#211]
새로 할당받은 gpu에서 이전에 작업해놓은 코드를 실행했을 때, 다음과 같은 에러가 발생합니다. 제 코드말고도 baby_Unet에서 leaderboard_eval.py할 때도 동일한 에러가 발생하는데, gpu의 문제일까요? 영상에서 나오는 pip list, install은 동일하게 실행했습니다. 

<img width="845" alt="스크린샷 2023-08-10 오후 8 07 38" src="https://github.com/LISTatSNU/FastMRI_challenge/assets/102167841/16cab9bf-6fe9-474f-9bbd-8e353f4a8bac">

**Comment by HyeonbeomChoi** [comment]
iabeng98 노드입니다

**Comment by wogur110** [comment]
안녕하세요, 2023 SNU FastMRI Challenge 조교 배재혁입니다.
해당 노드를 확인해 본 결과, opencv-python 버전을 다운그레이드 (3.8.0.76 -> 3.8.0.74) 했을 때 해당 문제 (import cv2 에서 에러가 나는 문제) 가 해결됨을 확인하였습니다. 우선은 정상적으로 코드가 돌아가는 것으로 보이니 한번 확인해주시면 감사하겠습니다.

감사합니다.
배재혁 드림

**Comment by HyeonbeomChoi** [comment]
정상적으로 돌아갑니다! 감사합니다.
