### ISSUE TITLE
about:blank#blocked 오류

### ISSUE THREAD

**Issue by robin5310** [LISTatSNU/FastMRI_challenge#214]
quicktools로 주피터 노트북에 들어가려 하면 about:blank#blocked 오류가 발생하며 접속되지 않습니다.

다른 기기, 브라우저로 시도해도 발생하고, 노드는 iabeng94 입니다.

**Comment by wogur110** [comment]
안녕하세요. 현재 모든 노드에서 jupyter notebook을 통한 접속이 되지 않고 있어서 원인을 파악 중입니다.
원인 파악 후 연락드리겠습니다.
감사합니다.
배재혁 드림

**Comment by wogur110** [comment]
해당 이슈 해결되었다고 합니다. 감사합니다.

**Comment by robin5310** [comment]
정상 작동 확인했습니다! 감사합니다.
