### ISSUE TITLE
branch name 관련 문의입니다.

### ISSUE THREAD

**Issue by HYUNHONOH98** [LISTatSNU/FastMRI_challenge#233]
안녕하세요. 팀 에머라이의 노현호 참가자입니다.

branch name 이 **baby_varnet** 인 이유가 따로 있을까요? 

[E2EVarNet](https://arxiv.org/pdf/2004.06688) 논문에서 구현된 Varnet 과 차이가 있는걸까요? 감사합니다.

**Comment by jslee525** [comment]
안녕하세요, 2024 SNU FastMRI 조교 이준성입니다.
작년 branch 이름을 그대로 참고해서 baby라 붙였습니다.
크게 신경쓰지 않으셔도 될 것 같습니다.
감사합니다.
