### ISSUE TITLE
Dataset 오프라인 수령 관련 문의입니다.

### ISSUE THREAD

**Issue by HYUNHONOH98** [LISTatSNU/FastMRI_challenge#234]
안녕하세요, 팀 에머라이의 노현호입니다.

301 에서 오프라인 데이터셋 수령이 가능하다고 하셨는데, 언제 어디로 가면 수령할 수 있나요?

감사합니다.

**Comment by jslee525** [comment]
안녕하세요, 2024 SNU FastMRI 조교 이준성입니다.
현재 내부 논의 중이라 빠른 시일 내에 결정하여 공지드리겠습니다.
감사합니다.
