### ISSUE TITLE
GPU Server 관련

### ISSUE THREAD

**Issue by jslee525** [LISTatSNU/FastMRI_challenge#236]
안녕하세요, 2024 SNU FastMRI 조교 이준성입니다.

Vessl 서버 할당을 모두 완료했습니다.
아직 튜토리얼 영상이 편집 중이라 유튜브에 올라가 있진 않은 상태입니다.
빠른 시일 내에 Vessl 및 Baseline 사용법을 메일로 공지드리겠습니다.

현재 GPU는 총 98대(IABENG05 ~ IABENG102) 할당되었습니다.

감사합니다.
이준성 드림

**Comment by hyukjunlim** [comment]
안녕하세요. IABENG68 GPU를 할당받았는데, vessl에서 run을 시켜 확인해 보니 home 디렉토리에 Data 디렉토리가 없는 것으로 보여, 데이터가 제대로 올라갔는지 확인차 질문드립니다.

**Comment by jslee525** [comment]
안녕하세요,

Vessl에서 경로 세팅을 해주어야 합니다.
자세한 것은 곧 업로드될 Vessl 튜토리얼을 확인해주세요.

감사합니다.
