### ISSUE TITLE
개발 환경 설정 관련 질문

### ISSUE THREAD

**Issue by starioKim** [LISTatSNU/FastMRI_challenge#241]
안녕하세요. github/vessl에 초기 환경 세팅 방식에 관해 질문이 있습니다.
제가 이해한 바로는 여기에 올라와있는 FastMRI_challenge를 fork하여 제 깃헙 계정으로 복사해오고 이를 로컬 컴퓨터에 clone 해오는 방식 등을 통해 코딩을 진행하고 train 등의 파일을 완성한 이후에는 
https://www.youtube.com/watch?v=5ZVKDiDr-4U
해당 영상에서 한 것과 동일하게 제 계정에서 코딩하여 수정한 깃헙 파일을 clone한 뒤에 학습을 진행하는 것 같은데요..  제가 제대로 이해한 것인지 궁금합니다.

너무 기초적인 질문이라 죄송합니다..ㅎㅎ

**Comment by jslee525** [comment]
안녕하세요, 2024 SNU FastMRI 조교 이준성입니다.

편하신 대로 하셔도 됩니다.
영상에서 설명드린 것은 Baseline Code를 사용하는 방법입니다.
이후에 직접 코드 파일을 메일로 받을 것이기 때문에, 말씀하신대로 fork를 하셔도 무방합니다.

감사합니다.
이준성 드림

**Comment by starioKim** [comment]
빠른 답변 감사드립니다!

그러면 코딩 자체는 로컬에서 한 뒤 깃헙에 올려 vessl에서 컴파일만 진행하는 방법과 vessl jupyter를 이용해 직접 코딩하는 방식 모두 가능한 것인가요?

**Comment by yxxshin** [comment]
안녕하세요,

네 맞습니다. 궁극적으로 같은 방법이기 때문에 두 방법 다 가능합니다.
다만 후자의 경우, 꼭 로컬 컴퓨터로도 백업을 해 두시기 바랍니다.

감사합니다.

**Comment by starioKim** [comment]
답변 감사드립니다!
