### ISSUE TITLE
Current cuda device:  0 관련

### ISSUE THREAD

**Issue by Giventicket** [LISTatSNU/FastMRI_challenge#43]
vessl에서 youtube 설명 그대로 work space를 할당하고 train.py를 run하고 나니
Current cuda device:  0
으로 출력이 나오는 것을 확인했습니다.
 
gpu 할당된 instance를 받았는데 cuda device가 0인 것이 의아해서 issue 올립니다.
답변 기다리겠습니다.

**Comment by espanic** [comment]
https://yonghyuc.wordpress.com/2019/08/06/pytorch-cuda-gpu-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0/

이거 확인하시면 될 듯 싶네요

**Comment by Giventicket** [comment]
index 였군요.. 감사합니다! issue close 하겠습니다.
