### ISSUE TITLE
Vessl workspace delete 관련 문의입니다

### ISSUE THREAD

**Issue by james0248** [LISTatSNU/FastMRI_challenge#49]
workspace 설정을 다시 하고 싶어서 workspace를 delete 하려고 하는데, delete 버튼이 비활성화되어있는 문제가 있습니다. 또한, terminate 버튼을 눌러도 아무 변화가 없어 문의드립니다.
<img width="102" alt="Screen Shot 2022-07-09 at 19 23 13" src="https://user-images.githubusercontent.com/38637195/178101684-55c9b062-069c-44b1-9a7f-820a9c71765d.png">
버튼 화면 첨부합니다

**Comment by HynwLee** [comment]
stop -> edit 해 보시기 바랍니다.
