### ISSUE TITLE
팀원이 2명인 경우 ssh 질문

### ISSUE THREAD

**Issue by kb5kch2** [LISTatSNU/FastMRI_challenge#51]
안녕하세요

팀원이 2명일 때 각각 ssh 키를 발급받아 GPU 서버에 접속하려고 했는데 한 명만 접속이 가능하고 나머지 한 명은 Permission Denied 오류가 뜹니다.

둘 중 하나의 ssh 키를 삭제하고 동일한 ssh로 서로 다른 두 컴퓨터에서 접속하려고 해도 동일한 오류가 뜹니다.

2명이 같은 workspace에 동시에 접속할 수 없는 건가요? 아니면 저희가 설정을 잘못한 건가요?

**Comment by ImDohun** [comment]
서로 다른 컴퓨터에서 Host를(Hostname이 아닌) 다르게 써서 오류를 해결했습니다

**Comment by hippothewild** [comment]
안녕하세요.

workspace는 기본적으로 개인을 위한 작업공간으로 설계되어, 각 workspace의 ssh access는 해당 workspace를 만든 유저가 보유한 ssh key를 기준으로 관리하고 있습니다.
두 명 이상이 한 workspace의 ssh access를 필요로 하실 경우, workspace를 만드실 유저(A)가 ssh key를 발급 후 해당 키를 다른 유저(B)에게 공유해서, workspace에 manual ssh access를 하는 방식으로 접속이 가능합니다.

![Screen Shot 2022-07-11 at 4 34 09 PM](https://user-images.githubusercontent.com/3176340/178212275-ca66b4e0-97eb-4235-aa12-85fb2901ae3c.png)

**Comment by keepTaeBorn** [comment]
@kb5kch2 안녕하세요, 같은 문제를 해결하고 있는 중인데요, 혹시 두 사람 각각 ssh key를 발급받은 경우 두 사람이 연결한 remote 포트가 같은 경우에도 권한 문제가 생기지 않으셨을까요? 그리고 서로 다른 컴퓨터에서 Host를(Hostname이 아닌) 다르게 쓰셨다는 게 무슨 뜻인지 설명해주실 수 있을까요? 감사합니다:)

**Comment by kb5kch2** [comment]
Port 번호는 같아도 오류가 발생하지 않았습니다.

저희가 마주한 오류 흐름을 다 알려드리겠습니다.
1. 서로 다른 두 컴퓨터에서 각각 ssh를 발급받았을 때 Permission Denied 오류
2. 서로 다른 두 컴퓨터에서 하나의 ssh를 복사하여 접속했을 때 오류
3. 1번에서 Hostname이 아닌 Host를 서로 다른 두 컴퓨터에서 다르게 설정했을 때 오류 없음
