### ISSUE TITLE
train data에 image 데이터가 존재하지 않습니다

### ISSUE THREAD

**Issue by james0248** [LISTatSNU/FastMRI_challenge#59]
얼마전에 서버에 접속했을 때는 image data가 존재했었는데, 현재는 kspace 데이터만 남아있는 것을 확인했습니다. 어떻게 하면 되는지 알려주시면 감사하겠습니다.

**Comment by daeyongshin** [comment]
안녕하세요. 
공과대학 정보화지원실 신대용 조교입니다.

확인해보니 해당 워크스테이션에 말씀하신대로 image data가 존재하지 않는 것을 확인하였습니다. 현재 image data 재배포 중이니 끝나면 다시 댓글 남기도록 하겠습니다.

감사합니다.

**Comment by daeyongshin** [comment]
배포 완료되었습니다.
