### ISSUE TITLE
서버 Workspace 삭제 문의

### ISSUE THREAD

**Issue by hckim012** [LISTatSNU/FastMRI_challenge#82]
python 버전을 높여서 다시 설치하고자 해서 workspace를 다시 만들려고 하는데 workspace 삭제 버튼이 비활성화되어 있습니다. workspace 삭제를 해주실수 있나요?
감사합니다.

**Comment by HynwLee** [comment]
팀명을 알려 주시기 바랍니다. 감사합니다.

**Comment by hckim012** [comment]
팀명은 KJ이고 계정 이름은 james0248입니다. 감사합니다.

2022년 7월 21일 (목) 오후 8:49, HynwLee ***@***.***>님이 작성:

**Comment by HynwLee** [comment]
Terminate 완료했습니다.

**Comment by hckim012** [comment]
감사합니다! issue 닫겠습니다.
