### ISSUE TITLE
데이터 오류 질문

### ISSUE THREAD

**Issue by kb5kch2** [LISTatSNU/FastMRI_challenge#85]
안녕하세요

저희가 갖고 있는 데이터 중 이상한 데이터를 발견하여 질문 드립니다.
사진의 왼쪽은 k-space, 오른쪽은 reconstruction 사진인데요, 이런 brain slice data도 존재하나요?
첨부한 사진은 train/kspace/brain10.h5의 14번 index sliced image입니다.

![화면 캡처 2022-07-22 152154](https://user-images.githubusercontent.com/87764851/180376399-70705d54-e3f7-487d-955a-df077ff14a0f.png)

혹시나 하여 정상 사진도 같이 첨부합니다.
같은 파일의 1번 index 사진입니다.
![image](https://user-images.githubusercontent.com/87764851/180376600-c9caf56e-40e1-407a-bbba-bb7c2c42d376.png)

**Comment by jonghoyi** [comment]
한 슬라이스라면 가장 위쪽 슬라이스여서 머리가 없는 슬라이스였을 수 있습니다.

**Comment by kb5kch2** [comment]
머리가 작아서 뇌가 아닌 빈 공간을 촬영한 것으로 이해하면 되나요?

또, 이런 데이터는 학습 시 제외해야 할 것 같은데, 제외하고 학습시켜도 되나요?

**Comment by jonghoyi** [comment]
네 그렇게 하면 됩니다.
