### ISSUE TITLE
kspace 데이터에 대한 SSIM 계산시 dynamic range 문의

### ISSUE THREAD

**Issue by orange-fritters** [LISTatSNU/FastMRI_challenge#99]
unet의 경우, input이 이미지이기 때문에 h5py 내부의 attrs['max']를 사용하여 SSIM의 dynamic range를 설정해준다고 이해했습니다.
(transform.py의 maximum 부분에 이 dynamic 값이 들어간다고 이해했습니다)
하지만, kspace의 경우 별도의 attrs가 존재하지 않는 것을 확인했습니다. 
loss_function의 SSIMLoss 클래스가 (이미지1, 이미지2, data_range)를 받는데 
이 때 kspace의 data_range를 어떻게 구할 수 있을지 여쭙고 싶습니다...!

**Comment by ahagyue** [comment]
Kspace의 data range가 필요한 이유를 제가 정확히 이해하지는 못했지만 직접 max혹은 min값을 구하시면 될 것 같습니다
